DROP SCHEMA IF EXISTS PUBLIC CASCADE;
CREATE SCHEMA IF NOT EXISTS PUBLIC;

-- auto-generated definition
CREATE TABLE TESTERSJOURNAL_USERS
(
  id         SERIAL      NOT NULL
    CONSTRAINT test_users_pkey
    PRIMARY KEY,
  login      VARCHAR(50) NOT NULL
    CONSTRAINT test_users_login_key
    UNIQUE,
  password   VARCHAR(50) NOT NULL,
  createdate TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- begin TESTERSJOURNAL_DEVICE
CREATE TABLE IF NOT EXISTS TESTERSJOURNAL_DEVICE (
  ID                SERIAL4      NOT NULL,
  VERSION           INTEGER,
  CREATE_TS         TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CREATED_BY        VARCHAR(50),
  UPDATE_TS         TIMESTAMP,
  UPDATED_BY        VARCHAR(50),
  DELETE_TS         TIMESTAMP,
  DELETED_BY        VARCHAR(50),
  --
  NAME_DEVICE       VARCHAR(255) NOT NULL,
  TESTING_ID        INTEGER,
  STATE             INTEGER,
  DEVICE_OS_ID      INTEGER  ,
  SCREEN_RESOLUTION VARCHAR(255),
  DESCRIPTION       VARCHAR(255),
  --
  PRIMARY KEY (ID)
);

-- end TESTERSJOURNAL_DEVICE

-- begin RSJOURNAL_OPERATION_SYSTEM
CREATE TABLE IF NOT EXISTS TESTERSJOURNAL_OPERATION_SYSTEM (
  ID          SERIAL4      NOT NULL,
  VERSION     INTEGER      NOT NULL,
  CREATE_TS   TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CREATED_BY  VARCHAR(50),
  UPDATE_TS   TIMESTAMP,
  UPDATED_BY  VARCHAR(50),
  DELETE_TS   TIMESTAMP,
  DELETED_BY  VARCHAR(50),
  --
  NAME        VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  --
  PRIMARY KEY (ID)
);
-- end TESTERSJOURNAL_OPERATION_SYSTEM

-- begin TESTERSJOURNAL_TESTING
CREATE TABLE IF NOT EXISTS TESTERSJOURNAL_TESTING (
  ID         SERIAL4   NOT NULL,
  VERSION    INTEGER   NOT NULL,
  CREATE_TS  TIMESTAMPTZ DEFAULT now(),
  CREATED_BY VARCHAR(50),
  UPDATE_TS  TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  DELETE_TS  TIMESTAMP,
  DELETED_BY VARCHAR(50),
  --
  USER_ID    INTEGER   NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME   TIMESTAMP,
  --
  PRIMARY KEY (ID)
);
ALTER TABLE TESTERSJOURNAL_DEVICE
  ADD CONSTRAINT FK_TESTERSJOURNAL_DEVICE_TESTING FOREIGN KEY (TESTING_ID) REFERENCES TESTERSJOURNAL_TESTING (ID);

ALTER TABLE TESTERSJOURNAL_DEVICE
  ADD CONSTRAINT FK_TESTERSJOURNAL_DEVICE_DEVICE_OS FOREIGN KEY (DEVICE_OS_ID) REFERENCES TESTERSJOURNAL_OPERATION_SYSTEM (ID);

ALTER TABLE TESTERSJOURNAL_TESTING
  ADD CONSTRAINT testersjournal_testing_test_users_id_fk
FOREIGN KEY (user_id) REFERENCES TESTERSJOURNAL_USERS (id) ;

INSERT INTO TESTERSJOURNAL_USERS (login, password) VALUES ('test1', 'password1');

INSERT INTO TESTERSJOURNAL_TESTING (version, create_ts, created_by, update_ts, updated_by, delete_ts, deleted_by, user_id, start_time, end_time)
VALUES
  (2, '2018-05-24 13:05:54.316000', 'asd', '2018-05-24 13:05:54.316000', 'asd', '2018-05-24 13:05:54.316000', 'asd', 1,
   '2018-05-24 13:05:54.316000', '2018-05-24 13:05:54.316000');

INSERT INTO TESTERSJOURNAL_OPERATION_SYSTEM (version, create_ts, created_by, update_ts, updated_by, delete_ts, deleted_by, name, description)
VALUES
  (2, '2018-05-24 13:05:54.316000', 'a', '2018-05-24 13:05:54.316000', 'b', '2018-05-24 13:05:54.316000', 'c',
   'd', 'n');

INSERT INTO TESTERSJOURNAL_DEVICE (version, create_ts, created_by, name_device, testing_id, state, device_os_id, screen_resolution, description)
VALUES
  ('1', '2018-05-24 13:04:45.719000', 'Первый девайс','HUAWEI', 1, 1, 1, '800 Х 1200', 'asd');

-- ALTER TABLE TESTERSJOURNAL_TESTING
--   ADD CONSTRAINT FK_TESTERSJOURNAL_TESTING_USER FOREIGN KEY (USER_ID) REFERENCES SEC_USER (ID)
-- end TESTERSJOURNAL_TESTING
