-- begin TESTERSJOURNAL_DEVICE

;
create index IDX_TESTERSJOURNAL_DEVICE_TESTING on TESTERSJOURNAL_DEVICE (TESTING_ID);
create index IDX_TESTERSJOURNAL_DEVICE_DEVICE_OS on TESTERSJOURNAL_DEVICE (DEVICE_OS_ID);
-- end TESTERSJOURNAL_DEVICE
-- begin TESTERSJOURNAL_TESTING
;
create index IDX_TESTERSJOURNAL_TESTING_USER on TESTERSJOURNAL_TESTING (USER_ID)
-- end TESTERSJOURNAL_TESTING
